# load("@rules_python//python:defs.bzl", "py_library")
load("@python//3.11:defs.bzl", py_binary_3_11= "py_binary")

py_binary_3_11(
    name = "arxml_parsing",
    srcs = ["arxml_parsing.py","container.py","export_database.py"],
    visibility = ["//visibility:public"],
)
